name: Cargo Build & Test

on: [push, pull_request]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: RustWatchman - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
      - name: Create Release Binary
        run: cargo build --release
      - name: Create Release Archive
        run: tar -czf rust-watchman-${{ matrix.toolchain }}.tar.gz target/release/librustwatchman.rlib
      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rust-watchman-${{ matrix.toolchain }}.tar.gz
          asset_name: rust-watchman-${{ matrix.toolchain }}.tar.gz
          asset_content_type: application/gzip
