name: Create Release and Upload Assets

on:
  release:
    types: [created]

jobs:
  upload_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup update stable && rustup default stable
      - run: cargo build --release
      - run: tar -czf rust-watchman-stable.tar.gz target/release/librustwatchman.rlib
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./rust-watchman-stable.tar.gz
          asset_name: rust-watchman-stable.tar.gz
          asset_content_type: application/gzip
